### ISSUE TITLE
请问chatbot的MultiAgent是用什么框架实现的？

### ISSUE THREAD

**Issue by lemon-little** [codefuse-ai/codefuse-chatbot#11]
请问chatbot的MultiAgent是用什么框架实现的？

**Comment by lightislost** [comment]
我们调研了github中多数的multi-agent框架，包括不限于metagpt、autogen、xagent、memgpt等，对他们的优缺点进行了分析，汲取它们优秀的框架机制，然后自研了我们chatbot里面的一套multi-agent框架。里面包含了一系列核心要素来使框架拥有更高的灵活度，以及更便捷的配置使用能力。

**Comment by buliugucloud** [comment]
> 我们调研了github中多数的multi-agent框架，包括不限于metagpt、autogen、xagent、memgpt等，对他们的优缺点进行了分析，汲取它们优秀的框架机制，然后自研了我们chatbot里面的一套multi-agent框架。里面包含了一系列核心要素来使框架拥有更高的灵活度，以及更便捷的配置使用能力。

Regarding the implementation of your multi-agent framework, which part of the code does it pertain to? Could you provide an example in the code showcasing how to use the framework? Thank you!

**Comment by lightislost** [comment]
> Regarding the implementation of your multi-agent framework, which part of the code does it pertain to? Could you provide an example in the code showcasing how to use the framework? Thank you!

You can view the codes of all modules from  ~/dev_opsgpt/connector and find corresponding usage examples in the path  ~/examples/agent_examples.
