### ISSUE TITLE
请问如何接入已有的大模型接口？

### ISSUE THREAD

**Issue by ReinhartLee** [codefuse-ai/codefuse-chatbot#12]
我们公司已经部署了一个codellama的大模型服务，并提供了统一的API。请问我该如何将该API集成进来？

**Comment by lightislost** [comment]
https://github.com/codefuse-ai/codefuse-chatbot/blob/main/sources/readme_docs/fastchat.md

现在已经更新了LLM接入的相关代码，可参考这部分的文档完成接入
