### ISSUE TITLE
程序启动不成功有关问题

### ISSUE THREAD

**Issue by lemon-little** [codefuse-ai/codefuse-chatbot#13]
在容器服务器上运行程序
## 配置内容
<img width="442" alt="image" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/53484050/8776b6f5-4fee-48fb-9032-51ea6dad1b63">

- 其他按照readme文档配置

## 问题
<img width="665" alt="image" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/53484050/8c22f7f5-5881-4b7a-969e-32898d0e66b0">

无法打开弹出的连接

**Comment by lemon-little** [comment]
# 在windows直接启动程序，把容器启动和沙盒都关掉后，出现如下问题
<img width="596" alt="880222fee43022b8d17df38ed2b5705" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/53484050/39549393-51bd-4181-890e-468b674bf606">

请问这是什么原因导致的问题？换了机器也没部署成功

**Comment by lemon-little** [comment]
windows试运行‘streamlit run webui.py ’，发现如下问题

<img width="604" alt="image" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/53484050/4de85302-8d42-42d3-a654-6af92507a8fc">

请问要如何解决该问题？

**Comment by lightislost** [comment]
@lemon-little 
~/devops_gpt/webui/dialogue.py
```
# 加载YAML文件
webui_yaml_filename = "webui_zh.yaml" if True else "webui_en.yaml"
with open(os.path.join(cur_dir, f"yamls/{webui_yaml_filename}"), 'r', encoding='utf-8') as f:
    try:
        webui_configs = yaml.safe_load(f)
    except yaml.YAMLError as exc:
        print(exc)

```


文件编码问题，只要用utf-8读取就可以了

**Comment by lemon-little** [comment]
<img width="599" alt="image" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/53484050/4cf5a0cd-6324-46c3-8899-c61c38a933a4">

请问这是什么问题导致的？

**Comment by lightislost** [comment]
@lemon-little   确认这个接口是否能够启动， http://localhost:7862/sdfiles/list

~/examples/start.py #227
if check_process("service/sdfile_api.py"):
    subprocess.Popen(sdfile_sh, shell=True)

**Comment by lemon-little** [comment]
> @lemon-little 确认这个接口是否能够启动， http://localhost:7862/sdfiles/list
> 
> ~/examples/start.py #227 if check_process("service/sdfile_api.py"): subprocess.Popen(sdfile_sh, shell=True)

运行start.py 后打开 http://localhost:7862/sdfiles/list显示无法访问此网站

**Comment by lightislost** [comment]
建议：
排查1：
```
cd  codefuse-chatbot
python dev_opsgpt/service/sdfile_api.py

# 确认 是否 打开 http://localhost:7862/sdfiles/list
# 如果能打开，则不是脚本问题
```
排查2：
```
# 如果  server_config.py#DOCKER_SERVICE = True， 在执行 start.py后进入容器进行日志排查
winpty docker exec -it devopsgpt_webui bash # 进入容器，windwos系统需要winpty其它系统不需要
more logs/sdfile_api.log # 排查日志
```

**Comment by lemon-little** [comment]
> 建议： 排查1：
> 
> ```
> cd  codefuse-chatbot
> python dev_opsgpt/service/sdfile_api.py
> 
> # 确认 是否 打开 http://localhost:7862/sdfiles/list
> # 如果能打开，则不是脚本问题
> ```
> 
> 排查2：
> 
> ```
> # 如果  server_config.py#DOCKER_SERVICE = True， 在执行 start.py后进入容器进行日志排查
> winpty docker exec -it devopsgpt_webui bash # 进入容器，windwos系统需要winpty其它系统不需要
> more logs/sdfile_api.log # 排查日志
> ```

对于排查1：能够打开
<img width="313" alt="image" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/53484050/a8d8c332-6344-4d1c-b9ec-b7ac564bb3fc">

对于排查2：我的运行设置为 server_config.py#DOCKER_SERVICE = **False**

**Comment by lightislost** [comment]
@lemon-little   
```python
server_config.py#DOCKER_SERVICE = False
```
在 `python start.py` 后，在  ~/codefuse-chatbot/logs 查看对应的日志  ，sdfile_api.log

**Comment by lemon-little** [comment]
> @lemon-little
> 
> ```python
> server_config.py#DOCKER_SERVICE = False
> ```
> 
> 在 `python start.py` 后，在 ~/codefuse-chatbot/logs 查看对应的日志 ，sdfile_api.log

<img width="572" alt="image" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/53484050/e7922f74-7020-4ba4-b335-e1e495b340c7">
这是log

**Comment by lemon-little** [comment]
> @lemon-little
> 
> ```python
> server_config.py#DOCKER_SERVICE = False
> ```
> 
> 在 `python start.py` 后，在 ~/codefuse-chatbot/logs 查看对应的日志 ，sdfile_api.log
<img width="395" alt="image" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/53484050/abae0133-64e5-4295-979d-84e5c41c909c">

更换GB2312编码重新打开如图所示

**Comment by lightislost** [comment]
@lemon-little 
这个错误是在`windows`的 `cmd`下启动所造成的
1、如果一定要在`cmd`下启动，需要修改stary.py#212~215相关代码，`nohup` 改成 `start /B`
2、用git bash 来执行 `python start.py`

**Comment by lemon-little** [comment]
<img width="898" alt="image" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/53484050/383d48cb-927c-4596-973f-2f2cf6e12f67">


现在可以成功启动，但是不知道为什么，当我进行连续对话，仅对话第2次就无法输出。
第一，大模型API显示接收到问题请求，并给出应答
第二，以下内容是git bash的输出截图

<img width="618" alt="image" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/53484050/77f449b5-9d34-4505-a27c-d34b2082e60e">

<img width="623" alt="image" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/53484050/09606009-49c5-40ea-8dae-2d20bd111b56">

<img width="614" alt="image" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/53484050/3c636aa6-a850-4e2e-a1fa-69c1000d86c5">

请问我要如何排查？

**Comment by lightislost** [comment]
agent_chat.py#chat_iterator函数入参：message和momery包含相关的的返回信息
