### ISSUE TITLE
默认对代码的embedding模型是什么呢？

### ISSUE THREAD

**Issue by JudeZzz1997** [codefuse-ai/codefuse-chatbot#15]
一般的文本embedding模型在代码数据上效果极差，导致使用自然语言搜索编程语言（code search任务）效果很差，请问你们是如何解决这个问题的？

**Comment by bingxuchai** [comment]
我们是内部通过大模型产出代码的自然语言解读，避免了直接针对代码做embedding，检索的时候也是去匹配问题和自然语言解读来获取到代码原文的

**Comment by JudeZzz1997** [comment]
> 我们是内部通过大模型产出代码的自然语言解读，避免了直接针对代码做embedding，检索的时候也是去匹配问题和自然语言解读来获取到代码原文的

再请问一下，对于较长的代码文件，分割方面有什么trick嘛

**Comment by bingxuchai** [comment]
可以考虑通过程序分析的手段来按照类，方法层面来分割，如果遇到某个方法本身就非常长的话，可以看看能不能让大模型来帮助将长方法分隔成负责不同功能的代码块了

**Comment by lightislost** [comment]
暂时先关闭 issue，后面还有问题可重新打开

**Comment by uaoioy1o** [comment]
> 我们是内部通过大模型产出代码的自然语言解读，避免了直接针对代码做embedding，检索的时候也是去匹配问题和自然语言解读来获取到代码原文的

请问检索获取代码原文是以怎么样的一个形式放到正式query当中，用纯代码吗，还是代码描述+代码
