### ISSUE TITLE
Having trouble launching

### ISSUE THREAD

**Issue by Ethan-2004** [codefuse-ai/codefuse-chatbot#23]
I'm having trouble running this command
`python llm_api.py`
how can i solve it
---
### This is an error message
![2024-02-17_155728](https://github.com/codefuse-ai/codefuse-chatbot/assets/133947788/a63b8265-e99f-4821-a969-540bbf986823)

**Comment by lightislost** [comment]
Thank you for your test. It's "import error".  We have fix this error.
