### ISSUE TITLE
有关数据处理器、知识图谱等并未上线。

### ISSUE THREAD

**Issue by Joe-2002** [codefuse-ai/codefuse-chatbot#26]
### Checked other resources

- [X] I searched the Codefuse documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Summary 💡

🗂️ Data Processor: 数据处理器，轻松完成文档载入、数据清洗，及文本切分，整合不同来源的数据。
🔤 Text Embedding & Index:：文本嵌入索引，用户可以轻松上传文件进行文档检索，优化文档分析过程。
🗄️ Vector Database & Graph Database: 向量与图数据库，提供灵活强大的数据管理解决方案。
📝 Prompt Control & Management:：Prompt 控制与管理，精确定义智能体的上下文环境。

**Comment by lightislost** [comment]
数据处理器这块儿按text_splitter切分的能力是有的，可以支持一些通用文档的上传管理。
然后向量和图数据库目前是用在代码库上，没在RAG上进行透出，内部还在持续打磨这块工作，近期不会透出

**Comment by Joe-2002** [comment]
> 数据处理器这块儿按text_splitter切分的能力是有的，可以支持一些通用文档的上传管理。 然后向量和图数据库目前是用在代码库上，没在RAG上进行透出，内部还在持续打磨这块工作，近期不会透出

希望优先考虑在RAG上使用，比较期待效果。
RAG也是最常用的大模型应用场景，其受数据处理和向量的影响较大，且知识图谱也是个不错的尝试。
望尽早支持，从年前观望到现在了。

**Comment by lightislost** [comment]
感谢关注这块儿的工作，这个是在做的，后面有能够放出的版本也会及时放出。

**Comment by LiujunjieALiling** [comment]
@lightislost  请问这个 https://github.com/codefuse-ai/codefuse-chatbot/issues/37 关注一下呢，代码检索的时候周末避免这个问题呢

**Comment by guojie0701** [comment]
现在有放出吗？真心希望有一个阿里这样大厂开源的、真实可用的运维大模型底座
