### ISSUE TITLE
希望增加星火、百度、GLM等开源api的实现

### ISSUE THREAD

**Issue by Joe-2002** [codefuse-ai/codefuse-chatbot#27]
### Checked other resources

- [X] I searched the Codefuse documentation with the integrated search.
- [x] I used the GitHub search to find a similar question and didn't find it.

**Comment by lightislost** [comment]
在~/examples/model_workers里有zhipu.py(GLM)、xinghuo.py(星火)、qianfan.py(百度)的接口实现（接口代码也是直接来自于Langchain-Chatchat。），可参考 https://github.com/codefuse-ai/codefuse-chatbot/blob/main/sources/readme_docs/fastchat.md  进行使用。

注：这部分接口代码由于缺少相关Api权限，在本项目中未测试。

**Comment by Joe-2002** [comment]
> 在~/examples/model_workers里有zhipu.py(GLM)、xinghuo.py(星火)、qianfan.py(百度)的接口实现（接口代码也是直接来自于Langchain-Chatchat。），可参考 https://github.com/codefuse-ai/codefuse-chatbot/blob/main/sources/readme_docs/fastchat.md 进行使用。
> 
> 注：这部分接口代码由于缺少相关Api权限，在本项目中未测试。

我测试后，成功运行后，是否可以提交PR

**Comment by lightislost** [comment]
非常欢迎提交PR，我们也希望一部分超出内部资源之外的工作能够被补齐
