### ISSUE TITLE
Search_engine_chat() got an unexpected keyword argument 'pi_key'

### ISSUE THREAD

**Issue by GeorgeGalway** [codefuse-ai/codefuse-chatbot#29]
### Checked other resources

- [X] I searched the Codefuse documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in Codefuse-Repos rather than my code.
- [X] I added a very descriptive title to this issue.

### System Info

Windows

### Code Version

Latest Release

### Description

![image](https://github.com/codefuse-ai/codefuse-chatbot/assets/24989842/13f9d222-3f77-462b-977d-8dfda301fa7b)
![image](https://github.com/codefuse-ai/codefuse-chatbot/assets/24989842/63797585-7f28-474c-b76b-6b9d3d8c5490)
单词拼写错误

### Example Code

![image](https://github.com/codefuse-ai/codefuse-chatbot/assets/24989842/63797585-7f28-474c-b76b-6b9d3d8c5490)

### Error Message and Stack Trace (if applicable)

![image](https://github.com/codefuse-ai/codefuse-chatbot/assets/24989842/8675cbb2-ee2d-42fd-a6c9-f21e2471e6a4)
这种问题其实我可以自己提个PR

**Comment by lightislost** [comment]
@GeorgeGalway 感谢您的反馈和修复。这对后续的使用者很有帮助👍
