### ISSUE TITLE
希望增加devops-model的大模型

### ISSUE THREAD

**Issue by ggjjlldd** [codefuse-ai/codefuse-chatbot#31]
### Checked other resources

- [X] I searched the Codefuse documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

**Comment by lightislost** [comment]
codefuse-devops-model的底座是qwen，所以本身就可以支持的

**Comment by lightislost** [comment]
如果这边没有问题的话，在本周五会对issue进行关闭，有其它问题可以再次打开
