### ISSUE TITLE
启动成功了一半？

### ISSUE THREAD

**Issue by wxxcarl** [codefuse-ai/codefuse-chatbot#38]
### Checked other resources

- [X] I searched the Codefuse documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in Codefuse-Repos rather than my code.
- [X] I added a very descriptive title to this issue.

### System Info

MacOS

### Code Version

Latest Release

### Description

bash start.sh启动配置页面成功，然后启动服务报错：
<img width="780" alt="image" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/3860334/93851a47-a8e8-4f94-ba1a-94f71a23c3a7">
，对话界面自动打开，但是页面报错：
<img width="728" alt="image" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/3860334/a3f23988-8603-4513-98c9-a5ba07e6284f">

### Example Code

bash start.sh

**Comment by lightislost** [comment]
这个应该是 sdfile_api 服务没启动起来，可以看下这个日志sdfile_api.log

**Comment by DingZhaohai** [comment]
try:
    # ignore these content
    from zdatafront import client, monkey, OPENAI_API_BASE
    # patch openai sdk
    monkey.patch_openai()
    secret_key = base64.b64decode('xx').decode('utf-8')
    # zdatafront 提供的统一加密密钥
    client.aes_secret_key = secret_key
    # zdatafront 分配的业务标记
    client.visit_domain = os.environ.get("visit_domain")
    client.visit_biz = os.environ.get("visit_biz")
    client.visit_biz_line = os.environ.get("visit_biz_line")
except Exception as e:
    OPENAI_API_BASE = "https://api.openai.com/v1"
    logger.error(e)
    pass

**Comment by lightislost** [comment]
这段忽略即可，按照启动页配置对应的openai密钥即可

**Comment by wxxcarl** [comment]
还是不行，我注释了上面那段，然后写死了OPENAI_API_BASE 和 OPENAI_API_KEY，
其它按照https://github.com/codefuse-ai/codefuse-chatbot/blob/main/sources/readme_docs/start.md进行配置，DOCKER_SERVICE = False，SANDBOX_DO_REMOTE = False，
然后python start.py，
还是报一样的错。
另外二维码过期了，能否更新一下
