### ISSUE TITLE
希望提供星火接口、百度接口，开原大模型（GLM3、百川、Intern等）

### ISSUE THREAD

**Issue by Joe-2002** [codefuse-ai/codefuse-chatbot#4]
希望提供星火接口、百度接口，开原大模型（GLM3、百川、Intern等）

**Comment by lemon-little** [comment]
希望提供通义千问API支持

**Comment by lightislost** [comment]
https://github.com/codefuse-ai/codefuse-chatbot/blob/main/sources/readme_docs/fastchat.md

现在已经更新了LLM接入的相关代码，可参考这部分的文档完成接入  @lemon-little @Joe-2002
