### ISSUE TITLE
感谢开源，但问题实在太多了

### ISSUE THREAD

**Issue by wxxcarl** [codefuse-ai/codefuse-chatbot#40]
### Checked other resources

- [X] I searched the Codefuse documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in Codefuse-Repos rather than my code.
- [X] I added a very descriptive title to this issue.

### System Info

MacOS

### Code Version

Latest Release

### Description

可能我是新手的原因，对python不怎么懂，使我寸步难行。
目前只能对话
1. 新建知识库没反应，页面闪一下，就恢复原样了，未看到报错，sdfiles接口200OK
2. 构建代码知识库报错：`OSError: [Errno 30] Read-only file system: '/syao_graph.json'`

### Example Code

`_client.py[line:1026] - INFO: HTTP Request: GET http://127.0.0.1:7862/sdfiles/list "HTTP/1.1 200 OK"`
`_client.py[line:1026] - INFO: HTTP Request: GET http://127.0.0.1:7862/sdfiles/download?filename=&save_filename= "HTTP/1.1 200 OK"`

**Comment by wxxcarl** [comment]
有时候又有反应，报错：
`OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like sentence-transformers/text2vec-base-chinese is not the path to a directory containing a file named config.json.`
像是网路问题，就开了梯子，然后启动就有问题：
 ERROR    | webui.utils:get:125 - Using SOCKS proxy, but the 'socksio' package is not installed. Make sure to install httpx using `pip install httpx[socks]`.
 ERROR    | webui.utils:_check_httpx_json_response:667 - 'NoneType' object has no attribute 'json'

**Comment by wxxcarl** [comment]
我下载了text2vec-base-chinese到本地，知识库创建了(开始还是没反应，但换个名字再创建就可以成功)，导入文档之后，选择文档又报错了：
`ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`
```js
File "/Users/xiaoxiang/Library/Python/3.9/lib/python/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
File "/Users/xiaoxiang/work/gpt/codefuse-chatbot/examples/webui.py", line 92, in <module>
    pages[selected_page]["func"](api)
File "/Users/xiaoxiang/work/gpt/codefuse-chatbot/examples/webui/document.py", line 282, in knowledge_page
    file_name, file_path = file_exists(kb, selected_rows)
File "/Users/xiaoxiang/work/gpt/codefuse-chatbot/examples/webui/document.py", line 49, in file_exists
    if selected_rows:
File "/Users/xiaoxiang/Library/Python/3.9/lib/python/site-packages/pandas/core/generic.py", line 1466, in __nonzero__
    raise ValueError(
````
python新手，动手能力实在有限，心累

**Comment by lightislost** [comment]
建议删除后~Codefuse-chatbot/knowledge_base 、~Codefuse-chatbot/code_base 重新执行看看。可能是某一步骤的执行让数据库存在记录偏差导致
