### ISSUE TITLE
在线demo页面

### ISSUE THREAD

**Issue by xxllp** [codefuse-ai/codefuse-chatbot#41]
### Checked other resources

- [X] I searched the Codefuse documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Summary 💡

如题，需要提供一个能够直接尝试的页面系统。而且主页的演示视频竟然是外网youtube~

**Comment by lightislost** [comment]
暂无计划，后续有计划会在[projects](https://github.com/orgs/codefuse-ai/projects/1) 同步
