### ISSUE TITLE
Windows 环境和Docker 环境运行均报错

### ISSUE THREAD

**Issue by fl1906** [codefuse-ai/codefuse-chatbot#5]
Windows环境报错如下
<img width="463" alt="image" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/73702449/0c102e45-12d4-476b-9382-0b78304c872d">

Windows Docker 环境报错如下
<img width="609" alt="image" src="https://github.com/codefuse-ai/codefuse-chatbot/assets/73702449/93f7ed36-2899-4ca9-8696-17599dec89a2">

**Comment by lightislost** [comment]
第一个不太清楚，有没有更多信息来判断？

第二个报错是你的docker没连接上，你可以通过确认docker ps来判断是否正确执行docker命令
