### ISSUE TITLE
运行cd examples && python start.py或python dev_opsgpt/service/llm_api.py后报错，说是没有数据文件：data/neluba_data

### ISSUE THREAD

**Issue by quida01** [codefuse-ai/codefuse-chatbot#7]
运行cd examples && python start.py或python dev_opsgpt/service/llm_api.py后报错，说是没有数据文件：data/neluba_data

FileNotFoundError: [Errno 2] No such file or directory: '/media/models/model-tools/codefuse-chatbot-main/data/neluba_data'

**Comment by lightislost** [comment]
感谢反馈。
这是由于model_config.py.example 里面 自动化创建文件错误的问题

修改如下代码即可，后续会更新这个错误
# 
for _path in [LOG_PATH, SOURCE_PATH, KB_ROOT_PATH, NLTK_DATA_PATH, JUPYTER_WORK_PATH, WEB_CRAWL_PATH, NELUBA_PATH]:
    if not os.path.exists(_path):
        os.makedirs(_path, exist_ok=True)
