### ISSUE TITLE
Difficulties were encountered in accessing the model

### ISSUE THREAD

**Issue by jjjxusbx** [codefuse-ai/codefuse-chatbot#9]
My processor uses these，13th Gen Intel(R) Core(TM) i5-13500H   2.60 GHz
If so, do I have to install the Python 3.9.18 editor? Request answer
![屏幕截图 2023-12-15 090728](https://github.com/codefuse-ai/codefuse-chatbot/assets/146902099/02ce793e-4771-4420-abbf-029e1bcca8f7)

**Comment by lightislost** [comment]
We recommend using the Python 3.9.18 editor if you want to use Fastchat to access more local private models. Of course， you have gpu device.
